//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("Ok", Namespace="CarblamSvc", IsNullable=false)]
public partial class OkType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
public partial class OrderHistoryInfoType {
    
    private long createdTicksField;
    
    private bool createdTicksFieldSpecified;
    
    private long confirmedTicksField;
    
    private bool confirmedTicksFieldSpecified;
    
    private long acceptedTicksField;
    
    private bool acceptedTicksFieldSpecified;
    
    private long loadingTicksField;
    
    private bool loadingTicksFieldSpecified;
    
    private long loadedTicksField;
    
    private bool loadedTicksFieldSpecified;
    
    private long deliveredTicksField;
    
    private bool deliveredTicksFieldSpecified;
    
    private long finishedTicksField;
    
    private bool finishedTicksFieldSpecified;
    
    private long cancelledTicksField;
    
    private bool cancelledTicksFieldSpecified;
    
    /// <remarks/>
    public long CreatedTicks {
        get {
            return this.createdTicksField;
        }
        set {
            this.createdTicksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreatedTicksSpecified {
        get {
            return this.createdTicksFieldSpecified;
        }
        set {
            this.createdTicksFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public long ConfirmedTicks {
        get {
            return this.confirmedTicksField;
        }
        set {
            this.confirmedTicksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ConfirmedTicksSpecified {
        get {
            return this.confirmedTicksFieldSpecified;
        }
        set {
            this.confirmedTicksFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public long AcceptedTicks {
        get {
            return this.acceptedTicksField;
        }
        set {
            this.acceptedTicksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AcceptedTicksSpecified {
        get {
            return this.acceptedTicksFieldSpecified;
        }
        set {
            this.acceptedTicksFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public long LoadingTicks {
        get {
            return this.loadingTicksField;
        }
        set {
            this.loadingTicksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LoadingTicksSpecified {
        get {
            return this.loadingTicksFieldSpecified;
        }
        set {
            this.loadingTicksFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public long LoadedTicks {
        get {
            return this.loadedTicksField;
        }
        set {
            this.loadedTicksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LoadedTicksSpecified {
        get {
            return this.loadedTicksFieldSpecified;
        }
        set {
            this.loadedTicksFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public long DeliveredTicks {
        get {
            return this.deliveredTicksField;
        }
        set {
            this.deliveredTicksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeliveredTicksSpecified {
        get {
            return this.deliveredTicksFieldSpecified;
        }
        set {
            this.deliveredTicksFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public long FinishedTicks {
        get {
            return this.finishedTicksField;
        }
        set {
            this.finishedTicksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FinishedTicksSpecified {
        get {
            return this.finishedTicksFieldSpecified;
        }
        set {
            this.finishedTicksFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public long CancelledTicks {
        get {
            return this.cancelledTicksField;
        }
        set {
            this.cancelledTicksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CancelledTicksSpecified {
        get {
            return this.cancelledTicksFieldSpecified;
        }
        set {
            this.cancelledTicksFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
public partial class ParcelInfoType {
    
    private string descriptionField;
    
    private double weightField;
    
    private double widthField;
    
    private double heightField;
    
    private double lengthField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("RegisterSpec", Namespace="CarblamSvc", IsNullable=false)]
public partial class RegisterSpecType {
    
    private string loginField;
    
    private string passwordField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("RequestActivationSpec", Namespace="CarblamSvc", IsNullable=false)]
public partial class RequestActivationSpecType {
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("ChangePasswordSpec", Namespace="CarblamSvc", IsNullable=false)]
public partial class ChangePasswordSpecType {
    
    private string newPasswordField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NewPassword {
        get {
            return this.newPasswordField;
        }
        set {
            this.newPasswordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("ChangeEmailSpec", Namespace="CarblamSvc", IsNullable=false)]
public partial class ChangeEmailSpecType {
    
    private string passwordField;
    
    private string oldEmailField;
    
    private string newEmailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OldEmail {
        get {
            return this.oldEmailField;
        }
        set {
            this.oldEmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NewEmail {
        get {
            return this.newEmailField;
        }
        set {
            this.newEmailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("ResetPasswordSpec", Namespace="CarblamSvc", IsNullable=false)]
public partial class ResetPasswordSpecType {
    
    private string loginField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("LoginSpec", Namespace="CarblamSvc", IsNullable=false)]
public partial class LoginSpecType {
    
    private string loginField;
    
    private string passwordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("ProfileFootprintInfo", Namespace="CarblamSvc", IsNullable=false)]
public partial class ProfileFootprintInfoType {
    
    private string loginField;
    
    private string emailFootprintField;
    
    private bool isActivatedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EmailFootprint {
        get {
            return this.emailFootprintField;
        }
        set {
            this.emailFootprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsActivated {
        get {
            return this.isActivatedField;
        }
        set {
            this.isActivatedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("OrderSpec", Namespace="CarblamSvc", IsNullable=false)]
public partial class OrderSpecType {
    
    private string fromAddressField;
    
    private LocationType fromLocationField;
    
    private string toAddressField;
    
    private LocationType toLocationField;
    
    private string confirmMessageField;
    
    private ParcelInfoType parcelField;
    
    private string receiverLoginField;
    
    /// <remarks/>
    public string FromAddress {
        get {
            return this.fromAddressField;
        }
        set {
            this.fromAddressField = value;
        }
    }
    
    /// <remarks/>
    public LocationType FromLocation {
        get {
            return this.fromLocationField;
        }
        set {
            this.fromLocationField = value;
        }
    }
    
    /// <remarks/>
    public string ToAddress {
        get {
            return this.toAddressField;
        }
        set {
            this.toAddressField = value;
        }
    }
    
    /// <remarks/>
    public LocationType ToLocation {
        get {
            return this.toLocationField;
        }
        set {
            this.toLocationField = value;
        }
    }
    
    /// <remarks/>
    public string ConfirmMessage {
        get {
            return this.confirmMessageField;
        }
        set {
            this.confirmMessageField = value;
        }
    }
    
    /// <remarks/>
    public ParcelInfoType Parcel {
        get {
            return this.parcelField;
        }
        set {
            this.parcelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ReceiverLogin {
        get {
            return this.receiverLoginField;
        }
        set {
            this.receiverLoginField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("UpdateLocationSpec", Namespace="CarblamSvc", IsNullable=false)]
public partial class LocationType {
    
    private double latitudeField;
    
    private double longitudeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("OrderInfo", Namespace="CarblamSvc", IsNullable=false)]
public partial class OrderInfoType {
    
    private OrderSpecType specField;
    
    private CarInfoType carField;
    
    private OrderHistoryInfoType historyField;
    
    private OrderStatusType statusField;
    
    private bool isMyOutcomeField;
    
    private bool isMyIncomeField;
    
    private bool isMyBaggageField;
    
    private long idField;
    
    /// <remarks/>
    public OrderSpecType Spec {
        get {
            return this.specField;
        }
        set {
            this.specField = value;
        }
    }
    
    /// <remarks/>
    public CarInfoType Car {
        get {
            return this.carField;
        }
        set {
            this.carField = value;
        }
    }
    
    /// <remarks/>
    public OrderHistoryInfoType History {
        get {
            return this.historyField;
        }
        set {
            this.historyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public OrderStatusType Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsMyOutcome {
        get {
            return this.isMyOutcomeField;
        }
        set {
            this.isMyOutcomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsMyIncome {
        get {
            return this.isMyIncomeField;
        }
        set {
            this.isMyIncomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsMyBaggage {
        get {
            return this.isMyBaggageField;
        }
        set {
            this.isMyBaggageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("CarInfo", Namespace="CarblamSvc", IsNullable=false)]
public partial class CarInfoType {
    
    private StartWorkSpecType specField;
    
    private LocationType locationField;
    
    /// <remarks/>
    public StartWorkSpecType Spec {
        get {
            return this.specField;
        }
        set {
            this.specField = value;
        }
    }
    
    /// <remarks/>
    public LocationType Location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("StartWorkSpec", Namespace="CarblamSvc", IsNullable=false)]
public partial class StartWorkSpecType {
    
    private string descriptionField;
    
    private string designationField;
    
    private double weightLimitField;
    
    private double widthField;
    
    private double heightField;
    
    private double lengthField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Designation {
        get {
            return this.designationField;
        }
        set {
            this.designationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double WeightLimit {
        get {
            return this.weightLimitField;
        }
        set {
            this.weightLimitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
public enum OrderStatusType {
    
    /// <remarks/>
    Created,
    
    /// <remarks/>
    Confirmed,
    
    /// <remarks/>
    Accepted,
    
    /// <remarks/>
    Loading,
    
    /// <remarks/>
    InProgress,
    
    /// <remarks/>
    Unloading,
    
    /// <remarks/>
    Done,
    
    /// <remarks/>
    Canceled,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("OrderInfoList", Namespace="CarblamSvc", IsNullable=false)]
public partial class OrderInfoListType {
    
    private OrderInfoType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OrderInfo")]
    public OrderInfoType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("CarInfoList", Namespace="CarblamSvc", IsNullable=false)]
public partial class CarInfoListType {
    
    private CarInfoType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CarInfo")]
    public CarInfoType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("Stamp", Namespace="CarblamSvc", IsNullable=false)]
public partial class StampInfoType {
    
    private long valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtendedErrorInfoType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("ErrorInfo", Namespace="CarblamSvc", IsNullable=false)]
public partial class ErrorInfoType {
    
    private string messageField;
    
    private string stackTraceField;
    
    private ErrorInfoType innerErrorField;
    
    private string typeNameField;
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public string StackTrace {
        get {
            return this.stackTraceField;
        }
        set {
            this.stackTraceField = value;
        }
    }
    
    /// <remarks/>
    public ErrorInfoType InnerError {
        get {
            return this.innerErrorField;
        }
        set {
            this.innerErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TypeName {
        get {
            return this.typeNameField;
        }
        set {
            this.typeNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="CarblamSvc")]
[System.Xml.Serialization.XmlRootAttribute("ExtendedErrorInfo", Namespace="CarblamSvc", IsNullable=false)]
public partial class ExtendedErrorInfoType : ErrorInfoType {
    
    private string rawErrorInfoField;
    
    /// <remarks/>
    public string RawErrorInfo {
        get {
            return this.rawErrorInfoField;
        }
        set {
            this.rawErrorInfoField = value;
        }
    }
}
